site_name: E1A
site_author: ElaBosak233
theme:
  name: "material"
  logo: assets/img/icon.svg
  favicon: assets/img/icon.svg
  custom_dir: overrides
  features:
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.footer
    - header.autohide
    - navigation.path
    - navigation.top
    - toc.follow
  language: "zh"
  palette:
        primary: "teal"
        accent: "teal"
repo_url: https://github.com/ElaBosak233/e1a.git
repo_name: ElaBosak233/e1a
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - glightbox
  - search
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ElaBosak233
copyright: >
  Copyleft &copy; 2023 <a href="https://github.com/ElaBosak233" target="_blank">@ElaBosak233</a>