site_name: E1A
site_author: ElaBosak233
theme:
  name: "material"
  logo: assets/img/icon.svg
  favicon: assets/img/icon.svg
  custom_dir: overrides
  features:
    # - announce.dismiss        # 通知关闭
    # - content.action.edit       # 编辑操作
    # - content.action.view       # 查看操作
    - content.code.annotate     # 代码注释
    - content.code.copy         # 复制代码
    - content.tabs.link         # 标签链接
    - content.tooltips          # 工具提示
    # - header.autohide         # 自动隐藏头部
    # - navigation.expand       # 展开导航
    - navigation.indexes        # 导航索引
    - navigation.instant      # 即时导航
    # - navigation.prune        # 导航修剪
    # - navigation.sections     # 导航节
    - navigation.tabs         # 导航标签
    # - navigation.tabs.sticky  # 固定导航标签
    - navigation.top            # 导航顶部
    - navigation.footer         # 导航底部
    - navigation.tracking       # 导航跟踪
    - search.highlight          # 搜索高亮
    # - search.share              # 搜索分享
    - search.suggest            # 搜索建议
    - toc.follow                # 目录跟随
    # - toc.integrate           # 目录整合
  language: "zh"
  palette:
        primary: "teal"
        accent: "teal"
  font:
    text: Noto Sans SC
    code: Roboto Mono
repo_url: https://github.com/ElaBosak233/e1a.git
repo_name: ElaBosak233/e1a
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
plugins:
  - glightbox
  - search
  - tags
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ElaBosak233
copyright: >
  Copyleft &copy; 2023 <a href="https://github.com/ElaBosak233" target="_blank">@ElaBosak233</a>